Repository aquasecurity/trivy-operator, pull requests merged in 2023-10, with the labels that each got.

#1550 chore: label pr by prefix update
  .github/workflows/pr-labeler.yaml
  .github/workflows/title_checker-labeler.yaml
Labels: misc

#1554 chore: merge label tasks
  .github/pr-prefix-labeler.yml
  .github/workflows/title_checker-labeler.yaml
Labels: misc

#1555 chore: add automatic release
  .github/release.yml
Labels: misc

#1556 chore: add automatic release-lint
  .github/release.yml
Labels: misc

#1552 docs: update link to the configuration page in kubectl page
  docs/getting-started/installation/kubectl.md
Labels: documentation

#1553 feat(manifests): add metrics component for static installation
  deploy/static/components/metrics/kustomization.yaml
  deploy/static/components/metrics/metrics.yaml
Labels: feature

#1563 chore: helm docs verify
  magefile.go
Labels: misc

#1562 feat: make headless service configurable
  deploy/helm/templates/monitor/service.yaml
  deploy/helm/values.yaml
Labels: feature

#1566 chore: separate build workflow
  .github/workflows/build.yaml
  .github/workflows/private-registries.yaml
Labels: misc

#1565 feat: node-collector resources config
  .github/workflows/build.yaml
  .github/workflows/private-registries.yaml
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  go.mod
  go.sum
  pkg/configauditreport/controller/node.go
  pkg/kube/object_test.go
  pkg/metrics/collector.go
  pkg/vulnerabilityreport/controller/trivyserver_test.go
Labels: feature

#1570 chore: remove workflow cache
  .github/workflows/chart-testing.yaml
Labels: misc

#1572 docs: update release process
  RELEASING.md
Labels: documentation

#1579 fix: vuln-id metric broken
  pkg/metrics/collector.go
Labels: bug

#1582 chore: release changlog
  .goreleaser.yaml
Labels: misc

#1583 docs: change command value fs to filesystem in private-registries tutorial
  docs/tutorials/private-registries.md
Labels: bug, documentation

#1576 fix(helm): add custom policies config
  deploy/helm/README.md
  deploy/helm/templates/configmaps/policies.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
Labels: bug

#1591 fix: add trivy-timeout on scan fs mode
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/plugin_test.go
Labels: bug

#1602 chore: bump go version
  .github/workflows/build.yaml
  .github/workflows/chart-testing.yaml
  .github/workflows/private-registries.yaml
  .github/workflows/release-snapshot.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
  itest/helper/helper.go
  itest/matcher/matcher.go
  itest/matcher/matcher_test.go
  pkg/configauditreport/builder.go
  pkg/configauditreport/builder_test.go
  pkg/exposedsecretreport/builder.go
  pkg/exposedsecretreport/builder_test.go
  pkg/infraassessment/builder.go
  pkg/infraassessment/builder_test.go
  pkg/kube/object_test.go
  pkg/metrics/collector_test.go
  pkg/plugins/trivy/filesystem.go
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/jobspec.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/plugin_test.go
  pkg/policy/policy_test.go
  pkg/rbacassessment/builder.go
  pkg/rbacassessment/builder_test.go
  pkg/sbomreport/builder.go
  pkg/sbomreport/builder_test.go
  pkg/utils/dateutil.go
  pkg/vulnerabilityreport/builder.go
  pkg/vulnerabilityreport/builder_test.go
Labels: misc
