Repository aquasecurity/trivy-operator, pull requests merged in 2023-12, with the labels that each got.

#1646 feat: kbom and k8s core component scan
  README.md
  deploy/helm/crds/aquasecurity.github.io_clustervulnerabilityreports.yaml
  deploy/helm/generated/role.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/getting-started/installation/helm.md
  docs/getting-started/installation/olm.md
  go.mod
  go.sum
  mkdocs.yml
  pkg/apis/aquasecurity/v1alpha1/register.go
  pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go
  pkg/apis/aquasecurity/v1alpha1/zz_generated.deepcopy.go
  pkg/configauditreport/controller/resource.go
  pkg/kube/object.go
  pkg/operator/cluster.go
  pkg/operator/cluster_test.go
  pkg/operator/operator.go
  pkg/operator/predicate/predicate.go
  pkg/operator/predicate/predicate_test.go
  pkg/plugins/trivy/image.go
  pkg/sbomreport/builder.go
  pkg/sbomreport/io.go
  pkg/trivyoperator/constants.go
  pkg/vulnerabilityreport/builder.go
  pkg/vulnerabilityreport/builder_test.go
  pkg/vulnerabilityreport/controller/scanjob.go
  pkg/vulnerabilityreport/controller/workload.go
  pkg/vulnerabilityreport/io.go
  tests/e2e/image-mode/workload/07-assert.yaml
Labels: feature

#1669 feat: trivy fs -include-dev-deps support
  deploy/helm/README.md
  deploy/helm/templates/configmaps/trivy.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  pkg/plugins/trivy/config.go
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/filesystem.go
  pkg/plugins/trivy/filesystem_test.go
Labels: feature

#1684 docs: remove duplicate entry in the CRDs list
  docs/getting-started/installation/helm.md
Labels: documentation

#1686 fix: typo in nav
  mkdocs.yml
Labels: bug

#1683 fix: sbom secret size limit
  pkg/vulnerabilityreport/controller/helper.go
  pkg/vulnerabilityreport/controller/helper_test.go
  pkg/vulnerabilityreport/controller/testdata/sbom.json
Labels: bug

#1712 fix: kubelet checks via config resource
  deploy/helm/README.md
  deploy/helm/templates/rbac/clusterrole.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  go.mod
  go.sum
Labels: bug

#1713 fix: missing reports on via cluster sbom cache
  deploy/helm/README.md
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  pkg/operator/etc/config.go
  pkg/operator/ttl_report.go
  pkg/vulnerabilityreport/controller/helper.go
  pkg/vulnerabilityreport/controller/scanjob.go
  pkg/vulnerabilityreport/controller/workload.go
Labels: bug

#1714 fix: hang node collector node shutdown
  go.mod
  go.sum
  pkg/configauditreport/controller/node.go
Labels: bug

#1715 chore: trivy 0.48.1 dep update
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/sbom-report.md
  go.mod
  go.sum
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/jobspec_test.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/testdata/fixture/alpine_sbom.json
  pkg/policy/policy.go
  pkg/policy/policy_test.go
  pkg/sbomreport/io.go
  pkg/vulnerabilityreport/controller/testdata/sbom.json
  tests/e2e/sbom-client-server/workload/00-sbom-pod.yaml
  tests/e2e/sbom-fs/workload/00-sbom-pod.yaml
  tests/e2e/sbom-standalone/workload/00-sbom-pod.yaml
Labels: misc

#1657 feat: add dbRepositoryUsername and dbRepositoryPassword for dbReposit…
  deploy/helm/README.md
  deploy/helm/templates/secrets/trivy.yaml
  deploy/helm/values.yaml
  pkg/plugins/trivy/config.go
  pkg/plugins/trivy/filesystem.go
  pkg/plugins/trivy/image.go
Labels: feature

#1726 feat: ingress resource on config-scan support
  pkg/configauditreport/controller/resource.go
  pkg/kube/object.go
Labels: feature
