Repository aquasecurity/trivy-operator, pull requests merged in 2023-11, with the labels that each got.

#1605 chore: bump chart testing
  .github/workflows/chart-testing.yaml
  .github/workflows/publish-helm-chart.yaml
  deploy/helm/README.md
  deploy/helm/values.yaml
Labels: misc

#1604 feat: Flag for changing default cache-dir parameter
  deploy/helm/README.md
  deploy/helm/templates/configmaps/trivy.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  pkg/plugins/trivy/config.go
  pkg/plugins/trivy/filesystem.go
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/plugin_test.go
Labels: feature

#1613 feat: Added AWS_REGION env for ECR images in the ClientServer mode
  pkg/plugins/trivy/image.go
Labels: feature

#1623 fix: handle trivy insecure database in ClientServer mode
  pkg/plugins/trivy/image.go
Labels: bug

#1625 docs: helm install
  docs/getting-started/installation/helm.md
Labels: documentation

#1633 fix: chart version
  docs/tutorials/grafana-dashboard.md
Labels: bug

#1634 docs: fix chart version
  docs/tutorials/private-registries.md
Labels: documentation

#1640 docs: Typo fix
  docs/getting-started/installation/olm.md
Labels: documentation

#1642 docs: modify README and docs landing page to reflect the same content
  README.md
  docs/index.md
Labels: documentation

#1644 fix: remove node selector
  go.mod
  go.sum
Labels: bug

#1641 docs: make small changes to the docs introduction
  CONTRIBUTING.md
  docs/docs/configuration-auditing/index.md
  docs/docs/crds/clustercompliance-report.md
  docs/docs/crds/clustercompliancedetail-report.md
  docs/docs/crds/configaudit-report.md
  docs/docs/crds/exposedsecret-report.md
  docs/docs/crds/infraassessment-report.md
  docs/docs/crds/rbacassessment-report.md
  docs/docs/index.md
  docs/docs/vulnerability-scanning/index.md
  docs/docs/vulnerability-scanning/private-registries.md
  docs/getting-started/installation/index.md
  docs/getting-started/installation/kubectl.md
  docs/getting-started/installation/olm.md
  mkdocs.yml
Labels: documentation

#1652 fix: ensure trivy cm default
  pkg/operator/operator.go
Labels: bug

#1643 feat: Add OS information to Vuln Reports and add optional image info metrics
  deploy/helm/README.md
  deploy/helm/crds/aquasecurity.github.io_vulnerabilityreports.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/vulnerability-report.md
  docs/tutorials/integrations/metrics.md
  itest/helper/helper.go
  pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go
  pkg/apis/aquasecurity/v1alpha1/zz_generated.deepcopy.go
  pkg/metrics/collector.go
  pkg/metrics/collector_test.go
  pkg/operator/etc/config.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/plugin_test.go
  pkg/plugins/trivy/testdata/fixture/exposedsecret_report.json
  pkg/plugins/trivy/testdata/fixture/full_report.json
  pkg/plugins/trivy/testdata/fixture/vulnerability_report.json
  pkg/vulnerabilityreport/io.go
  pkg/webhook/webhookreporter_test.go
Labels: feature

#1654 chore: add condition for docs publish
  .github/workflows/publish-helm-chart.yaml
Labels: misc

#1664 fix: scan job fail nil pointer
  pkg/plugins/trivy/plugin.go
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: bug
