Repository aquasecurity/trivy-operator, pull requests merged in 2024-05, with the labels that each got.

#2054 chore: bump trivy-0.51.1
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/sbom-report.md
  go.mod
  go.sum
  pkg/operator/operator.go
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/jobspec_test.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/testdata/fixture/alpine_sbom.json
  pkg/policy/loader.go
  pkg/policy/policy_test.go
  pkg/vulnerabilityreport/controller/testdata/sbom.json
  tests/e2e/sbom-client-server/workload/00-sbom-pod.yaml
  tests/e2e/sbom-fs/workload/00-sbom-pod.yaml
  tests/e2e/sbom-standalone/workload/00-sbom-pod.yaml
  tests/envtest/testdata/fixture/cronjob-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/daemonset-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/job-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/pod-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/replicaset-configauditreport-expected.yaml
Labels: misc

#2064 fix: trivy db repository credential set
  pkg/plugins/trivy/config.go
Labels: bug

#2074 fix: the use of embedded checks, fallback for air-gapped env.
  deploy/helm/README.md
  deploy/helm/templates/configmaps/trivy.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  pkg/configauditreport/plugin.go
  pkg/plugins/trivy/config.go
  pkg/policy/policy.go
  pkg/policy/policy_test.go
Labels: bug

#2077 fix: cves high and critical
  .github/workflows/build.yaml
  .github/workflows/chart-testing.yaml
  .github/workflows/private-registries.yaml
  .github/workflows/release.yaml
  go.mod
Labels: bug

#2075 fix: node-collector cves high critical
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  go.mod
  go.sum
Labels: bug

#2080 feat: filter container by regex
  deploy/helm/README.md
  deploy/helm/templates/configmaps/operator.yaml
  deploy/helm/values.yaml
  pkg/plugins/trivy/filesystem.go
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/plugin_test.go
  pkg/trivyoperator/config.go
  pkg/trivyoperator/config_test.go
  pkg/vulnerabilityreport/controller/workload.go
Labels: feature

#2081 chore: bump trivy 0.51.2
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/sbom-report.md
  go.mod
  go.sum
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/jobspec_test.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/testdata/fixture/alpine_sbom.json
  pkg/vulnerabilityreport/controller/testdata/sbom.json
  tests/e2e/sbom-client-server/workload/00-sbom-pod.yaml
  tests/e2e/sbom-fs/workload/00-sbom-pod.yaml
  tests/e2e/sbom-standalone/workload/00-sbom-pod.yaml
Labels: misc

#2093 chore: auto bump minor golang version
  .github/workflows/build.yaml
  .github/workflows/chart-testing.yaml
  .github/workflows/private-registries.yaml
  .github/workflows/release-snapshot.yaml
  .github/workflows/release.yaml
Labels: misc

#2100 fix: policies bundle insecure
  deploy/helm/README.md
  deploy/helm/templates/configmaps/operator.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  pkg/operator/operator.go
  pkg/trivyoperator/config.go
Labels: bug

#2107 fix: non completed containers with invalid stacktrace
  .gitignore
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: bug

#2112 fix: log failed container error
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: bug
