Repository aquasecurity/trivy-operator, pull requests merged in 2024-01, with the labels that each got.

#1729 fix: service monitor cause operator to crash
  pkg/metrics/collector.go
Labels: bug

#1732 feat: retrieve sbom specified sources from oci registries
  deploy/helm/README.md
  deploy/helm/templates/configmaps/trivy.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  pkg/plugins/trivy/config.go
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/filesystem.go
  pkg/plugins/trivy/image.go
Labels: feature

#1741 fix: Update trivy.yaml to support cve list
  deploy/helm/templates/configmaps/trivy.yaml
Labels: bug

#1746 fix: set audit config plugin trivy by default
  pkg/operator/envtest/suite_test.go
  pkg/operator/operator.go
  pkg/plugins/factory.go
  pkg/trivyoperator/config.go
  pkg/trivyoperator/config_test.go
Labels: bug

#1753 test: private registries
  tests/e2e/image-private-registries-config/workload/00-assert.yaml
  tests/e2e/image-private-registries-config/workload/00-pod.yaml
  tests/e2e/image-private-registries-config/workload/01-assert.yaml
  tests/e2e/image-private-registries-sa/data/workload/00-assert.yaml
  tests/e2e/image-private-registries-sa/data/workload/00-pod.yaml
  tests/e2e/image-private-registries-sa/data/workload/01-assert.yaml
  tests/e2e/image-private-registries-sa/manifests/sa.yaml
  tests/e2e/image-private-registries/workload/00-assert.yaml
  tests/e2e/image-private-registries/workload/00-pod.yaml
  tests/e2e/image-private-registries/workload/01-assert.yaml
Labels: testing

#1761 chore: bump trivy v0.48.2
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/sbom-report.md
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/jobspec_test.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/testdata/fixture/alpine_sbom.json
  pkg/vulnerabilityreport/controller/testdata/sbom.json
  tests/e2e/sbom-client-server/workload/00-sbom-pod.yaml
  tests/e2e/sbom-fs/workload/00-sbom-pod.yaml
  tests/e2e/sbom-standalone/workload/00-sbom-pod.yaml
Labels: misc

#1766 docs: updated managed registries on Azure with Workload Identities
  docs/docs/vulnerability-scanning/managed-registries.md
Labels: documentation

#1770 fix: cluster version support
  pkg/operator/operator.go
Labels: bug

#1785 test: e2e with sbom - fluky tests
  tests/config/client-server-sbom.yaml
  tests/config/fs-sbom.yaml
  tests/config/sbom-standalone.yaml
  tests/resources-cleanup.sh
Labels: testing

#1791 fix: update private-registries.md
  docs/tutorials/private-registries.md
Labels: bug

#1801 feat: allow configration of trivy-server pvc size
  deploy/helm/Chart.yaml
  deploy/helm/README.md
  deploy/helm/templates/trivy-server/statefulset.yaml
  deploy/helm/values.yaml
Labels: feature

#1802 docs: helm version
  README.md
Labels: documentation

#1804 fix: use of node selector param
  go.mod
  go.sum
Labels: bug

#1806 chore: disable cluster cache
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
Labels: misc
