Repository aquasecurity/trivy-operator, pull requests merged in 2024-03, with the labels that each got.

#1608 docs: add documentation on how to install trivy-operator in a ns with default deny-all netpols
  docs/getting-started/installation/troubleshooting.md
Labels: documentation

#1889 feat: Also publish chart to OCI registry
  .github/workflows/publish-helm-chart.yaml
  README.md
  docs/getting-started/installation/helm.md
  docs/index.md
  docs/tutorials/grafana-dashboard.md
Labels: feature

#1897 feat: trivy policies bundle support
  deploy/helm/README.md
  deploy/helm/templates/configmaps/operator.yaml
  deploy/helm/templates/secrets/operator.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  go.mod
  pkg/configauditreport/controller/helper.go
  pkg/configauditreport/controller/nodecollector.go
  pkg/configauditreport/controller/policyconfig.go
  pkg/configauditreport/controller/resource.go
  pkg/operator/envtest/suite_test.go
  pkg/operator/envtest/testdata/content/policies/kubernetes/lib/kubernetes.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/lib/utils.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/cisbenchmarks/apiserver/anonymous_auth.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/cisbenchmarks/apiserver/audit_log_maxage.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/cisbenchmarks/apiserver/audit_log_maxbackup.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/cisbenchmarks/apiserver/audit_log_maxsize.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/cisbenchmarks/apiserver/audit_log_path.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/cisbenchmarks/apiserver/event_rate_limit_plugin.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/cisbenchmarks/apiserver/kubelet_certificate_authority.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/cisbenchmarks/apiserver/profiling.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/cisbenchmarks/apiserver/security_context_deny_plugin.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/CPU_not_limited.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/CPU_requests_not_specified.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/capabilities_no_drop_all.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/default_security_context.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/file_system_not_read_only.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/manage_namespace_secrets.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/memory_not_limited.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/memory_requests_not_specified.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/runs_with_GID_le_10000.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/general/runs_with_UID_le_10000.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/pss/baseline/11_seccomp_profile_unconfined.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/pss/restricted/2_can_elevate_its_own_privileges.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/pss/restricted/3_runs_as_root.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/pss/restricted/5_runtime_default_seccomp_profile_not_set.rego
  pkg/operator/envtest/testdata/content/policies/kubernetes/policies/pss/restricted/6_drop_all_capabilities_only_add_net_bind_service.rego
  pkg/operator/envtest/testdata/fixture/cronjob-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/daemonset-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/job-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/pod-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/replicaset-configauditreport-expected.yaml
  pkg/operator/operator.go
  pkg/operator/ttl_report.go
  pkg/policy/loader.go
  pkg/policy/policy.go
  pkg/policy/policy_test.go
  pkg/policy/testdata/fixture/content/policies/kubernetes/lib/kubernetes.rego
  pkg/policy/testdata/fixture/content/policies/kubernetes/lib/utils.rego
  pkg/policy/testdata/fixture/content/policies/kubernetes/policies/general/attaching_pod_view_logs_realtime.rego
  pkg/trivyoperator/config.go
  pkg/vulnerabilityreport/controller/trivyserver.go
Labels: feature

#1903 feat: ssl-cert dir support on init containers and built-in server
  deploy/helm/templates/trivy-server/statefulset.yaml
  pkg/plugins/trivy/filesystem.go
  pkg/plugins/trivy/image.go
Labels: feature

#1910 docs: Improve documentation for ClusterVulnerabilityReports
  deploy/helm/README.md
  deploy/helm/values.yaml
  docs/docs/crds/clustervulnerability-report.md
Labels: documentation

#1917 fix: generate scan reports for individual completed containers when pod scan failed
  pkg/kube/resources.go
  pkg/kube/resources_test.go
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: bug

#1919 chore: update ignore file values example
  deploy/helm/values.yaml
Labels: misc

#1915 fix: support affinity for scan jobs
  deploy/helm/README.md
  deploy/helm/templates/configmaps/operator.yaml
  deploy/helm/values.yaml
  docs/getting-started/installation/configuration.md
  docs/settings.md
  go.mod
  go.sum
  pkg/configauditreport/controller/node.go
  pkg/trivyoperator/config.go
  pkg/trivyoperator/config_test.go
  pkg/vulnerabilityreport/builder.go
  pkg/vulnerabilityreport/controller/workload.go
Labels: bug

#1927 fix: node-collector respect pod requests/limits
  go.mod
  go.sum
  pkg/configauditreport/controller/node.go
Labels: bug

#1928 fix: load trivy-policies by config
  pkg/operator/operator.go
Labels: bug

#1929 feat: Helm, allow to define service type for metrics Service
  deploy/helm/README.md
  deploy/helm/templates/monitor/service.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
Labels: feature

#1935 fix: Controller-runtime Logger Fails to Initialize
  cmd/trivy-operator/main.go
Labels: bug

#1949 chore: bump trivy lib and scan-job v0.50.0
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/sbom-report.md
  go.mod
  go.sum
  pkg/apis/aquasecurity/v1alpha1/compliance_types.go
  pkg/compliance/io.go
  pkg/configauditreport/controller/helper.go
  pkg/configauditreport/controller/resource.go
  pkg/operator/cluster.go
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/jobspec_test.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/testdata/fixture/alpine_sbom.json
  pkg/policy/policy.go
  pkg/policy/policy_test.go
  pkg/vulnerabilityreport/controller/testdata/sbom.json
  tests/e2e/sbom-client-server/workload/00-sbom-pod.yaml
  tests/e2e/sbom-fs/workload/00-sbom-pod.yaml
  tests/e2e/sbom-standalone/workload/00-sbom-pod.yaml
Labels: misc
