Repository aquasecurity/trivy-operator, pull requests merged in 2024-04, with the labels that each got.

#1964 chore: clean-up un-used folders and files
  overrides/main.html
Labels: misc

#1966 fix: add appropriate info msg for not supported windows images
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: bug

#1967 fix: handle non sha256 digest
  go.mod
  go.sum
Labels: bug

#1974 fix: configure context timeout for sync resources
  pkg/operator/operator.go
Labels: bug

#1975 fix: add annotation job pod template spec
  go.mod
  go.sum
Labels: bug

#1980 fix: remove controller manager timeout
  pkg/operator/operator.go
Labels: bug

#1988 fix: Updates ignorePolicy comments in values.yaml
  deploy/helm/values.yaml
Labels: bug

#2000 fix: add policies download err msg and fallback to embeded
  pkg/policy/loader.go
  pkg/policy/policy.go
Labels: bug

#2001 fix(helm): trivy server value typo
  deploy/helm/templates/configmaps/trivy.yaml
Labels: bug

#2004 fix: better error handling for node config api data
  .github/workflows/build.yaml
  .github/workflows/chart-testing.yaml
  .github/workflows/private-registries.yaml
  .github/workflows/release-snapshot.yaml
  .github/workflows/release.yaml
  deploy/helm/README.md
  deploy/helm/crds/aquasecurity.github.io_clustercompliancereports.yaml
  deploy/helm/crds/aquasecurity.github.io_clusterconfigauditreports.yaml
  deploy/helm/crds/aquasecurity.github.io_clusterinfraassessmentreports.yaml
  deploy/helm/crds/aquasecurity.github.io_clusterrbacassessmentreports.yaml
  deploy/helm/crds/aquasecurity.github.io_clustersbomreports.yaml
  deploy/helm/crds/aquasecurity.github.io_clustervulnerabilityreports.yaml
  deploy/helm/crds/aquasecurity.github.io_configauditreports.yaml
  deploy/helm/crds/aquasecurity.github.io_exposedsecretreports.yaml
  deploy/helm/crds/aquasecurity.github.io_infraassessmentreports.yaml
  deploy/helm/crds/aquasecurity.github.io_rbacassessmentreports.yaml
  deploy/helm/crds/aquasecurity.github.io_sbomreports.yaml
  deploy/helm/crds/aquasecurity.github.io_vulnerabilityreports.yaml
  deploy/helm/generated/role.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  go.mod
  magefile.go
  pkg/apis/aquasecurity/v1alpha1/zz_generated.deepcopy.go
Labels: bug

#2005 docs: add information on running Helm Chart in client server mode
  docs/docs/vulnerability-scanning/trivy.md
Labels: documentation

#2006 feat: separate toleration setting for node-collector
  deploy/helm/README.md
  deploy/helm/templates/configmaps/operator.yaml
  deploy/helm/values.yaml
  pkg/configauditreport/controller/node.go
  pkg/trivyoperator/config.go
Labels: feature

#2012 docs: version callout
  docs/overrides/main.html
  mkdocs.yml
Labels: documentation

#2013 fix: log entry name on policy loader
  pkg/policy/loader.go
Labels: bug

#2017 fix: better handling for kubelet config
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
Labels: bug

#2023 sec: update go-getter to latest version
  go.mod
  go.sum
Labels: misc

#2037 chore: bump trivy-0.50.2
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/sbom-report.md
  go.mod
  go.sum
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/jobspec_test.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/testdata/fixture/alpine_sbom.json
  pkg/vulnerabilityreport/controller/testdata/sbom.json
  tests/e2e/sbom-client-server/workload/00-sbom-pod.yaml
  tests/e2e/sbom-fs/workload/00-sbom-pod.yaml
  tests/e2e/sbom-standalone/workload/00-sbom-pod.yaml
Labels: misc

#2027 feat(helm): only deploy ClusterComplianceReports if enabled
  deploy/helm/templates/specs/cis-1.23.yaml
  deploy/helm/templates/specs/nsa-1.0.yaml
  deploy/helm/templates/specs/pss-baseline.yaml
  deploy/helm/templates/specs/pss-restricted.yaml
Labels: feature

#2040 chore: bump k8s.io libs-0.30.0 & fix lint issues
  .github/workflows/build.yaml
  go.mod
  go.sum
  pkg/compliance/io.go
  pkg/configauditreport/io.go
  pkg/metrics/collector.go
  pkg/operator/cluster.go
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/jobspec.go
  pkg/utils/compressutil.go
  pkg/vulnerabilityreport/io.go
Labels: misc
