Repository aquasecurity/trivy-operator, pull requests merged in 2024-11, with the labels that each got.

#2301 chore: bump up trivy to v0.57.1
  .github/workflows/build.yaml
  .github/workflows/chart-testing.yaml
  .github/workflows/private-registries.yaml
  deploy/helm/README.md
  deploy/helm/crds/aquasecurity.github.io_clustervulnerabilityreports.yaml
  deploy/helm/crds/aquasecurity.github.io_vulnerabilityreports.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  go.mod
  go.sum
  pkg/operator/operator.go
  pkg/policy/loader.go
  pkg/policy/policy.go
  tests/envtest/suite_test.go
Labels: misc

#2292 fix: vuln scan success criteria met
  build/trivy-operator/Dockerfile
  pkg/configauditreport/controller/nodecollector.go
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: bug

#2321 chore: use mirror.gcr.io for trivy-check by default
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
Labels: misc

#2311 feat: add package purl in VulnerabilityReport CRD
  deploy/helm/crds/aquasecurity.github.io_clustervulnerabilityreports.yaml
  deploy/helm/crds/aquasecurity.github.io_vulnerabilityreports.yaml
  deploy/static/trivy-operator.yaml
  pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go
  pkg/vulnerabilityreport/io.go
Labels: feature

#2318 chore: bump up kind for k8s v1.31
  .github/workflows/build.yaml
  tests/e2e/cluster/workload/00-assert.yaml
  tests/itest/trivy-operator/behavior/behavior.go
Labels: misc
