Repository aquasecurity/trivy-operator, pull requests merged in 2024-06, with the labels that each got.

#2111 fix: Add scanJobAnnotations to the Job instead of just the Pod
  deploy/helm/README.md
  deploy/helm/values.yaml
  pkg/vulnerabilityreport/builder.go
  pkg/vulnerabilityreport/builder_test.go
Labels: bug

#2114 fix: set default value for useBuiltIntPolicies
  pkg/plugins/trivy/config.go
  pkg/vulnerabilityreport/builder.go
  pkg/vulnerabilityreport/builder_test.go
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: bug

#2115 chore: bump trivy 0.52.0
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/sbom-report.md
  go.mod
  go.sum
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/jobspec_test.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/testdata/fixture/alpine_sbom.json
  pkg/vulnerabilityreport/controller/testdata/sbom.json
  tests/e2e/sbom-client-server/workload/00-sbom-pod.yaml
  tests/e2e/sbom-fs/workload/00-sbom-pod.yaml
  tests/e2e/sbom-standalone/workload/00-sbom-pod.yaml
Labels: misc

#2122 fix: Added target field to metrics
  pkg/metrics/collector.go
  pkg/metrics/collector_test.go
Labels: bug

#2125 fix: failed to eval rego misconfig policy
  pkg/policy/loader.go
Labels: bug

#2138 fix: update olm defaults
  deploy/helm/README.md
  deploy/helm/values.yaml
  pkg/trivyoperator/config.go
Labels: bug

#2140 fix: Prevent grouped vulnerability entries by including target and package path
  pkg/metrics/collector.go
  pkg/metrics/collector_test.go
Labels: bug

#2152 chore: make operator policies-config optional
  deploy/helm/README.md
  deploy/helm/templates/configmaps/policies.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
Labels: misc

#2154 docs: fix typos in SbomReport docs
  docs/docs/crds/sbom-report.md
Labels: documentation

#2155 docs: add section on importing the Grafana dashboard using the Grafana Helm Chart
  docs/tutorials/grafana-dashboard.md
Labels: documentation

#2108 fix: helm param gcr service account auth
  deploy/helm/README.md
  deploy/helm/templates/configmaps/operator.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  pkg/plugins/trivy/image.go
  pkg/trivyoperator/config.go
Labels: bug
