Repository aquasecurity/trivy-operator, pull requests merged in 2024-02, with the labels that each got.

#1816 docs: Fix formatting in docs/tutorials/integrations/metrics.md
  docs/tutorials/integrations/metrics.md
Labels: documentation

#1817 chore: bump controller-runtime v0.17.0
  go.mod
  go.sum
  pkg/configauditreport/io_test.go
  pkg/exposedsecretreport/io_test.go
  pkg/infraassessment/io_test.go
  pkg/operator/ttl_report_test.go
  pkg/plugins/trivy/config_test.go
  pkg/rbacassessment/io_test.go
  pkg/sbomreport/io_test.go
  pkg/vulnerabilityreport/io_test.go
Labels: misc

#1824 fix: markdown url mistakes
  README.md
Labels: bug

#1819 feat: config for insecure server registry connection
  deploy/helm/README.md
  deploy/helm/templates/configmaps/trivy.yaml
  deploy/helm/values.yaml
Labels: feature

#1821 feat: added config for additional server annotations
  deploy/helm/README.md
  deploy/helm/templates/trivy-server/statefulset.yaml
  deploy/helm/values.yaml
Labels: feature

#1837 chore: use light goreleaser for snapshot releases
  .github/workflows/release-snapshot.yaml
Labels: misc

#1831 docs: Fix some typos and markdown links
  docs/docs/compliance/compliance.md
  docs/docs/configuration-auditing/built-in-policies.md
  docs/docs/configuration-auditing/index.md
  docs/docs/index.md
  docs/docs/vulnerability-scanning/index.md
  docs/docs/vulnerability-scanning/managed-registries.md
  docs/docs/vulnerability-scanning/private-registries.md
  docs/docs/vulnerability-scanning/trivy.md
  docs/getting-started/installation/configuration.md
  docs/getting-started/installation/helm.md
  docs/getting-started/installation/troubleshooting.md
  docs/getting-started/quick-start.md
  docs/index.md
  docs/settings.md
  docs/tutorials/grafana-dashboard.md
  docs/tutorials/integrations/metrics.md
  docs/tutorials/manage_access_to_security_reports.md
  docs/tutorials/private-registries.md
  docs/tutorials/writing-custom-configuration-audit-policies.md
Labels: documentation

#1840 docs: Change broken link from defsec to trivy-policies
  docs/docs/configuration-auditing/built-in-policies.md
Labels: documentation

#1845 feat: opa exception support
  pkg/configauditreport/controller/helper.go
Labels: feature

#1846 docs: Fix some links to other sections and websites
  docs/docs/configuration-auditing/built-in-policies.md
  docs/docs/index.md
  docs/docs/vulnerability-scanning/trivy.md
  docs/getting-started/installation/kubectl.md
  docs/index.md
  docs/tutorials/private-registries.md
  mkdocs.yml
Labels: documentation

#1849 feat: Enable passing values for operator through custom ConfigMap and/or Secrets
  deploy/helm/README.md
  deploy/helm/templates/configmaps/trivy-operator-config.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/getting-started/installation/configuration.md
Labels: feature

#1858 fix: false positive cis kubeletMakeIptablesUtilChainsArgumentSet
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  pkg/trivyoperator/config.go
Labels: bug

#1859 chore: bump trivy-0.49.1 lib
  deploy/helm/crds/aquasecurity.github.io_clustersbomreports.yaml
  deploy/helm/crds/aquasecurity.github.io_sbomreports.yaml
  deploy/static/trivy-operator.yaml
  go.mod
  go.sum
  pkg/apis/aquasecurity/v1alpha1/sbom_types.go
  pkg/apis/aquasecurity/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/cluster.go
  pkg/operator/envtest/testdata/fixture/cronjob-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/daemonset-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/job-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/pod-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/replicaset-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/replicationcontroller-configauditreport-expected.yaml
  pkg/operator/envtest/testdata/fixture/role-rbacassessment-expected.yaml
  pkg/plugins/trivy/jobspec_test.go
  pkg/plugins/trivy/testdata/fixture/alpine_sbom.json
  pkg/sbomreport/io.go
  pkg/sbomreport/util.go
  pkg/vulnerabilityreport/controller/testdata/sbom.json
  tests/e2e/sbom-client-server/workload/00-sbom-pod.yaml
  tests/e2e/sbom-fs/workload/00-sbom-pod.yaml
  tests/e2e/sbom-standalone/workload/00-sbom-pod.yaml
Labels: misc

#1869 fix: access to private regional gcr
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/image_test.go
  pkg/plugins/trivy/jobspec.go
Labels: bug

#1867 feat: add extra labels for operator and server controllers in Helm chart
  deploy/helm/README.md
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/trivy-server/statefulset.yaml
  deploy/helm/values.yaml
Labels: feature

#1871 feat: added configurable appProtocol to metrics service
  deploy/helm/README.md
  deploy/helm/templates/monitor/service.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
Labels: feature

#1875 feat: scan job secret ttl support
  deploy/helm/README.md
  deploy/helm/values.yaml
  pkg/apis/aquasecurity/v1alpha1/common_types.go
  pkg/operator/etc/config.go
  pkg/operator/operator.go
  pkg/operator/ttl_report.go
  pkg/vulnerabilityreport/builder.go
  pkg/vulnerabilityreport/controller/workload.go
  tests/config/image-private-registries.yaml
  tests/e2e/image-private-registries/workload/02-assert.yaml
Labels: feature
