Repository aquasecurity/trivy-operator, pull requests merged in 2024-07, with the labels that each got.

#2162 chore: bump github.com/hashicorp/go-getter-v1.7.5
  go.mod
  go.sum
Labels: misc

#2160 feat: dynamic compliance reports
  deploy/helm/README.md
  deploy/helm/crds/aquasecurity.github.io_clustercompliancereports.yaml
  deploy/helm/templates/specs/cis-1.23.yaml
  deploy/helm/templates/specs/eks-cis-1.4.yaml
  deploy/helm/templates/specs/k8s-cis-1.23.yaml
  deploy/helm/templates/specs/k8s-nsa-1.0.yaml
  deploy/helm/templates/specs/k8s-pss-baseline-0.1.yaml
  deploy/helm/templates/specs/k8s-pss-restricted-0.1.yaml
  deploy/helm/templates/specs/nsa-1.0.yaml
  deploy/helm/templates/specs/rke2-cis-1.24.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/sbom-report.md
  go.mod
  go.sum
  pkg/apis/aquasecurity/v1alpha1/compliance_types.go
  pkg/apis/aquasecurity/v1alpha1/zz_generated.deepcopy.go
  pkg/configauditreport/controller/node.go
  pkg/operator/operator.go
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/jobspec_test.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/testdata/fixture/alpine_sbom.json
  pkg/policy/loader.go
  pkg/policy/policy.go
  pkg/policy/policy_test.go
  pkg/vulnerabilityreport/controller/testdata/sbom.json
  tests/e2e/sbom-client-server/workload/00-sbom-pod.yaml
  tests/e2e/sbom-fs/workload/00-sbom-pod.yaml
  tests/e2e/sbom-standalone/workload/00-sbom-pod.yaml
  tests/envtest/suite_test.go
Labels: feature

#2168 fix: remove null checks values from ClusterComplianceReport in helm chart
  deploy/helm/templates/specs/eks-cis-1.4.yaml
  deploy/helm/templates/specs/k8s-cis-1.23.yaml
  deploy/helm/templates/specs/rke2-cis-1.24.yaml
Labels: bug

#2163 docs: Update configuration.md, added sbom generation flag
  docs/getting-started/installation/configuration.md
Labels: documentation

#2174 feat: add options to Helm chart to load Trivy config from custom configmap or secret
  deploy/helm/README.md
  deploy/helm/templates/trivy-server/statefulset.yaml
  deploy/helm/values.yaml
  docs/getting-started/installation/configuration.md
Labels: feature

#2179 chore: platform and type - no metadata values
  deploy/helm/templates/specs/k8s-cis-1.23.yaml
Labels: misc

#2180 chore: Update chart 0.24.1
  deploy/helm/Chart.yaml
  deploy/helm/README.md
Labels: misc

#2183 fix: Non-Unique Vulnerability Keys by Implementing Hashing of Structs
  pkg/metrics/collector.go
  pkg/metrics/collector_test.go
Labels: bug

#2190 docs: Grafana Dashboard - Add headless parameter to values.yaml
  docs/tutorials/grafana-dashboard.md
Labels: documentation
