Repository aquasecurity/trivy-operator, pull requests merged in 2025-06, with the labels that each got.

#2581 fix: enable more revive rules
  .golangci.yml
  pkg/compliance/clustercompliancereport.go
  pkg/compliance/io.go
  pkg/configauditreport/builder.go
  pkg/configauditreport/controller/nodecollector.go
  pkg/configauditreport/controller/resource.go
  pkg/configauditreport/io.go
  pkg/infraassessment/builder.go
  pkg/infraassessment/io.go
  pkg/kube/object.go
  pkg/operator/cluster.go
  pkg/operator/predicate/predicate.go
  pkg/rbacassessment/builder.go
  pkg/rbacassessment/io.go
  pkg/sbomreport/io.go
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: bug

#2564 feat: Add ability to control scanJobsInSameNamespace in the helm chart
  deploy/helm/README.md
  deploy/helm/templates/configmaps/operator.yaml
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
Labels: feature

#2582 fix: enable more go-critic rules
  .golangci.yml
  pkg/compliance/clustercompliancereport.go
  pkg/compliance/io.go
  pkg/configauditreport/controller/nodecollector.go
  pkg/configauditreport/controller/resource.go
  pkg/infraassessment/builder.go
  pkg/operator/cluster.go
  pkg/plugins/trivy/jobspec.go
  pkg/policy/policy.go
  pkg/rbacassessment/builder.go
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: bug

#2590 fix: login private registry instead of download JavaDB
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/jobspec.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/plugin_test.go
Labels: bug

#2605 chore: bump helm chart version
  README.md
  deploy/helm/Chart.yaml
  deploy/helm/README.md
  mkdocs.yml
Labels: misc

#2625 chore: update UBI to version 9.6-1750782676
  build/trivy-operator/Dockerfile.ubi9
Labels: misc

#2618 chore: bump up some deps
  go.mod
  go.sum
Labels: misc

#2619 chore: use a correct default repo for node-collector
  pkg/trivyoperator/config.go
Labels: misc
