Repository aquasecurity/trivy-operator, pull requests merged in 2025-01, with the labels that each got.

#2332 docs: Fix mage build command
  CONTRIBUTING.md
Labels: documentation

#2353 fix: Missing credentials for downloading the java-db from private registry
  pkg/plugins/trivy/config.go
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/plugin_test.go
Labels: bug

#2228 fix: config insecure when pull policy
  pkg/operator/operator.go
Labels: bug

#2272 fix: add TRIVY_JAVA_DB_REPOSITORY to trivy configmap
  deploy/helm/templates/configmaps/trivy.yaml
Labels: bug

#2371 chore: bump up Trivy version to fix CVE-2025-21613 and CVE-2025-21614
  .github/workflows/build.yaml
  .github/workflows/chart-testing.yaml
  .github/workflows/private-registries.yaml
  .github/workflows/release-snapshot.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
  pkg/utils/dateutil_test.go
Labels: bug, misc

#2241 fix: scanjob.customVolumesMount is not applied to the Built-Job
  pkg/vulnerabilityreport/builder.go
  pkg/vulnerabilityreport/builder_test.go
Labels: bug

#2288 feat: Add extraEnv option to Helm chart
  deploy/helm/README.md
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: bug, feature

#2382 chore: disable stale bot
  .github/workflows/stale-issues.yaml
Labels: misc

#2391 chore: bump up k8s deps to version 1.32
  go.mod
  go.sum
  pkg/vulnerabilityreport/builder_test.go
Labels: misc

#2286 fix: set `follow` to false when retrieving logs
  pkg/kube/logs.go
Labels: bug

#2399 fix: return the image manifest digest instead of image id
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/plugin_test.go
  pkg/plugins/trivy/testdata/fixture/exposedsecret_report.json
  pkg/plugins/trivy/testdata/fixture/full_report.json
  pkg/plugins/trivy/testdata/fixture/vulnerability_report.json
Labels: bug
