Repository aquasecurity/trivy-operator, pull requests merged in 2025-05, with the labels that each got.

#2528 chore(deps): bump up Trivy versions to v0.62.0
  go.mod
  go.sum
Labels: misc

#2538 docs: bump up Trivy version in the samples
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/configaudit-report.md
  docs/docs/crds/exposedsecret-report.md
  docs/docs/crds/infraassessment-report.md
  docs/docs/crds/rbacassessment-report.md
  docs/docs/crds/sbom-report.md
  docs/docs/crds/vulnerability-report.md
  docs/docs/design/design_trivy_file_system_scanner.md
  docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md
  docs/docs/design/ttl_scans.md
Labels: documentation

#2539 chore(ci): Free up space to build
  .github/workflows/release.yaml
Labels: misc

#2543 chore(ci): Free up additional space
  .github/workflows/build.yaml
  .github/workflows/release.yaml
Labels: misc

#2547 chore(deps): Update deps for trivy patch release
  go.mod
  go.sum
Labels: misc

#2533 docs(helm): Add trivy.existingSecret to README
  deploy/helm/README.md
  deploy/helm/values.yaml
Labels: documentation

#2521 docs: update trivy fs source
  docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md
Labels: documentation

#2553 test: add test cases for exclude images
  pkg/plugins/trivy/plugin_test.go
Labels: testing

#2558 chore(deps): bump golangci-lint to v2.1.2
  .github/workflows/build.yaml
  .golangci.yml
  magefile.go
  pkg/plugins/trivy/plugin_test.go
Labels: misc

#2559 chore(deps): bump golangci-lint to v2.1.6
  .golangci.yml
  magefile.go
  pkg/kube/object.go
Labels: misc

#2560 fix: enable staticcheck linters
  .golangci.yml
  pkg/configauditreport/controller/helper_test.go
  pkg/docker/config.go
  pkg/kube/logs.go
  pkg/operator/cluster.go
  pkg/plugins/trivy/config.go
  pkg/plugins/trivy/plugin_test.go
Labels: bug

#2569 fix(policy): remove oci artifact construction at startup
  pkg/operator/operator.go
Labels: bug

#2562 fix: enable contextcheck and usetesting linters
  .golangci.yml
  pkg/compliance/io.go
  pkg/compliance/io_test.go
  pkg/configauditreport/io_test.go
  pkg/exposedsecretreport/io_test.go
  pkg/infraassessment/io_test.go
  pkg/kube/object_test.go
  pkg/kube/secrets_test.go
  pkg/operator/cluster.go
  pkg/operator/operator.go
  pkg/operator/ttl_report.go
  pkg/operator/ttl_report_test.go
  pkg/plugins/trivy/config.go
  pkg/plugins/trivy/config_test.go
  pkg/policy/loader.go
  pkg/policy/policy_test.go
  pkg/rbacassessment/io_test.go
  pkg/sbomreport/io_test.go
  pkg/trivyoperator/config_test.go
  pkg/vulnerabilityreport/controller/trivyserver_test.go
  pkg/vulnerabilityreport/io_test.go
  pkg/webhook/webhookreporter_test.go
  tests/itest/helper/helper.go
  tests/itest/trivy-operator/behavior/behavior.go
Labels: bug

#2578 feat: copying over original alternate store writing to rebased main branch
  deploy/helm/README.md
  deploy/helm/templates/configmaps/trivy-operator-config.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/pvc.yaml
  deploy/helm/values.yaml
  docs/getting-started/installation/configuration.md
  docs/settings.md
  go.mod
  go.sum
  pkg/compliance/clustercompliancereport.go
  pkg/compliance/io.go
  pkg/configauditreport/builder.go
  pkg/configauditreport/controller/nodecollector.go
  pkg/configauditreport/controller/resource.go
  pkg/configauditreport/io.go
  pkg/infraassessment/builder.go
  pkg/infraassessment/io.go
  pkg/operator/cluster.go
  pkg/operator/etc/config.go
  pkg/rbacassessment/builder.go
  pkg/rbacassessment/io.go
  pkg/sbomreport/io.go
  pkg/vulnerabilityreport/controller/scanjob.go
Labels: feature
