Repository aquasecurity/trivy-operator, pull requests merged in 2025-09, with the labels that each got.

#2742 chore: bump up Trivy to version v0.66.0
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  docs/docs/crds/clustervulnerability-report.md
  docs/docs/crds/configaudit-report.md
  docs/docs/crds/exposedsecret-report.md
  docs/docs/crds/infraassessment-report.md
  docs/docs/crds/rbacassessment-report.md
  docs/docs/crds/sbom-report.md
  docs/docs/crds/vulnerability-report.md
  docs/docs/design/design_trivy_file_system_scanner.md
  docs/docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md
  docs/docs/design/ttl_scans.md
  go.mod
  go.sum
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/plugin_test.go
  pkg/vulnerabilityreport/controller/scanjob_test.go
Labels: misc

#2746 chore: bump up common k8s deps
  go.mod
  go.sum
  pkg/configauditreport/io_test.go
  pkg/exposedsecretreport/io_test.go
  pkg/infraassessment/io_test.go
  pkg/operator/ttl_report.go
  pkg/plugins/trivy/config_test.go
  pkg/rbacassessment/io_test.go
  pkg/sbomreport/io_test.go
  pkg/vulnerabilityreport/builder_test.go
  pkg/vulnerabilityreport/io_test.go
  pkg/webhook/webhookreporter_test.go
Labels: misc

#2745 fix(helm): always attempt to create ServiceMonitor when it is enabled
  deploy/helm/templates/monitor/servicemonitor.yaml
  deploy/helm/values.yaml
Labels: bug

#2667 feat: add labels to operator resources
  pkg/compliance/io.go
  pkg/configauditreport/builder.go
  pkg/configauditreport/builder_test.go
  pkg/exposedsecretreport/builder.go
  pkg/exposedsecretreport/builder_test.go
  pkg/infraassessment/builder.go
  pkg/infraassessment/builder_test.go
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/jobspec.go
  pkg/plugins/trivy/jobspec_test.go
  pkg/rbacassessment/builder.go
  pkg/rbacassessment/builder_test.go
  pkg/sbomreport/builder.go
  pkg/sbomreport/builder_test.go
  pkg/vulnerabilityreport/builder.go
  pkg/vulnerabilityreport/builder_test.go
  tests/envtest/controller_test.go
  tests/envtest/testdata/fixture/api-server-infraassessmentreport-expected.yaml
  tests/envtest/testdata/fixture/config-audit-ttl-historical.yaml
  tests/envtest/testdata/fixture/config-audit-ttl.yaml
  tests/envtest/testdata/fixture/cronjob-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/daemonset-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/job-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/pod-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/replicaset-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/replicationcontroller-configauditreport-expected.yaml
  tests/envtest/testdata/fixture/role-rbacassessment-expected.yaml
  tests/envtest/testdata/fixture/vulnerability-ttl.yaml
  tests/itest/helper/helper.go
Labels: misc, feature
