Repository aquasecurity/trivy-operator, pull requests merged in 2025-04, with the labels that each got.

#2500 test: improve integration tests
  magefile.go
  tests/itest/helper/helper.go
  tests/itest/trivy-operator/behavior/behavior.go
Labels: testing

#2480 chore(deps): bump golang.org/x/oauth2 from 0.25.0 to 0.27.0 - resolve CVE-2025-22868
  go.mod
  go.sum
Labels: misc

#2507 chore(deps): Bump `trivy-*` deps
  go.mod
  go.sum
  pkg/policy/loader.go
Labels: misc, deps

#2503 docs: change docs about ttl for scanned reports
  CONTRIBUTING.md
  docs/docs/design/ttl_scans.md
Labels: documentation

#2516 fix: skip excluded images in client server mode
  pkg/plugins/trivy/image.go
Labels: bug

#2520 fix(misconfig): ordering policies for hash
  pkg/policy/policy.go
  pkg/policy/policy_test.go
Labels: bug

#2526 chore: improve cache for policies
  pkg/configauditreport/controller/helper.go
  pkg/operator/operator.go
  pkg/policy/hash_bench_test.go
  pkg/policy/policy.go
  pkg/policy/policy_test.go
Labels: misc
