Repository aquasecurity/trivy-operator, pull requests merged in 2025-07, with the labels that each got.

#2637 fix(ci): use multiline syntax to print logs on failure
  .github/workflows/build.yaml
Labels: bug

#2642 docs: fix typo in RELEASING.md for Helm chart file name
  RELEASING.md
Labels: documentation

#2647 fix: bump helm to v3.18.4
  go.mod
  go.sum
Labels: bug

#2646 fix(deploy): remove hardcoded namespace from pvc-template
  deploy/helm/templates/pvc.yaml
Labels: bug

#2650 fix: add ubi9 images for nightly testing
  goreleaser-e2e.yaml
Labels: bug

#2652 fix: correct output for uncompressed logs
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/image_test.go
  pkg/plugins/trivy/plugin_test.go
Labels: bug

#2660 chore: bump up UBI 9 version to 9.6-1752587672
  build/trivy-operator/Dockerfile.ubi9
Labels: misc

#2670 fix: Do not error out on invalid rego policies if any
  pkg/policy/policy.go
  pkg/policy/policy_test.go
Labels: bug

#2678 chore: update for CVE-2025-6965
  build/trivy-operator/Dockerfile.ubi9
Labels: misc
