Repository aquasecurity/trivy-operator, pull requests merged in 2025-02, with the labels that each got.

#2406 chore: bump up Trivy version to v0.59.1
  .github/workflows/chart-testing.yaml
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/static/trivy-operator.yaml
  go.mod
  go.sum
Labels: misc, deps

#2424 fix(ci): update python action for Helm chart testing
  .github/workflows/publish-helm-chart.yaml
Labels: bug

#2445 docs: correct example ConfigMap for custom policy
  docs/tutorials/writing-custom-configuration-audit-policies.md
Labels: documentation

#2439 fix: update default values for configmap
  pkg/plugins/trivy/config_test.go
  pkg/plugins/trivy/plugin.go
  pkg/trivyoperator/config.go
Labels: bug

#2191 fix: sync stdout buffer to file
  pkg/plugins/trivy/image.go
  pkg/plugins/trivy/image_test.go
  pkg/plugins/trivy/plugin_test.go
  tests/envtest/testdata/fixture/cronjob-expected-scan.yaml
  tests/envtest/testdata/fixture/daemonset-expected-scan.yaml
  tests/envtest/testdata/fixture/job-expected-scan.yaml
  tests/envtest/testdata/fixture/pod-expected-scan.yaml
  tests/envtest/testdata/fixture/replicaset-expected-scan.yaml
  tests/envtest/testdata/fixture/replicationcontroller-expected-scan.yaml
  tests/envtest/testdata/fixture/statefulset-expected-scan.yaml
Labels: bug

#2397 feat: host aliases helm
  deploy/helm/README.md
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/trivy-server/statefulset.yaml
  deploy/helm/values.yaml
Labels: feature

#2458 fix(test): correct assertion and clean up test cases for eval policies
  pkg/policy/policy_test.go
  pkg/policy/testdata/fixture/builtin_role_result.json
  pkg/policy/testdata/fixture/buitin_result.json
Labels: bug

#2418 fix: parseImageRef tag absence issue when digest in imageRef
  pkg/plugins/trivy/plugin.go
  pkg/plugins/trivy/plugin_test.go
Labels: bug
